=== srecon/network-resource-monitoring/webserver-availability/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="username" type="xs:string"/>
	<xs:element name="smtp">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="host"/>
				<xs:element ref="port"/>
				<xs:element ref="username"/>
				<xs:element ref="password"/>
				<xs:element ref="from"/>
				<xs:element ref="subject"/>
				<xs:element ref="msgTemplate"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="smtp"/>
				<xs:element ref="notifications"/>
				<xs:element ref="report"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="servers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="server" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="server">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hostName"/>
				<xs:element ref="port"/>
				<xs:element ref="contextRoot"/>
				<xs:element ref="protocol"/>
				<xs:element ref="authconfig"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="format"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="protocol" type="xs:string"/>
	<xs:element name="port" type="xs:int"/>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="notifications">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="interval"/>
				<xs:element ref="emails"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="interval" type="xs:int"/>
	<xs:element name="hostName" type="xs:string"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="from" type="xs:string"/>
	<xs:element name="format" type="xs:string"/>
	<xs:element name="emails" type="xs:string"/>
	<xs:element name="contextRoot" type="xs:string"/>
	<xs:element name="subject" type="xs:string"/>
	<xs:element name="msgTemplate" type="xs:string"/>
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="servers"/>
				<xs:element ref="settings"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="param">
		<xs:complexType>
			<xs:attribute name="value" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>	
	<xs:element name="authconfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
</xs:schema>

=== srecon/network-resource-monitoring/conf/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
	<servers>
		<server>
			<hostName>sunny.fors.ru</hostName>
			<port>80</port>
			<contextRoot>archiva</contextRoot>
			<protocol>http</protocol>
			<authconfig/>
		</server>
		<server>
			<hostName>sunny.fors.ru</hostName>
			<port>80</port>
			<contextRoot>jenkins/j_acegi_security_check</contextRoot>
			<protocol>http</protocol>
			<authconfig>
				<param name="j_username" value="sahmed"/>
				<param name="j_password" value="xyz"/>
			</authconfig>
		</server>
		<server>
			<hostName>sunny.fors.ru</hostName>
			<port>80</port>
			<contextRoot>sonar11/sessions/new</contextRoot>
			<protocol>http</protocol>
			<authconfig>
				<param name="login" value="sahmed"/>
				<param name="password" value="xyz"/>
				<param name="commit" value="Log+in"/>
				<param name="remember_me" value="1"/>
			</authconfig>
		</server>
		<server>
			<hostName>sunny.fors.ru</hostName>
			<port>80</port>
			<contextRoot>jira/login.jsp</contextRoot>
			<protocol>http</protocol>
			<authconfig>
				<param name="os_username" value="sahmed"/>
				<param name="os_password" value="xyz"/>
				<param name="atl_token" value="e78a6e1fa29c510929dfcd0e14d4b0c00366cfe4"/>
				<param name="os_cookie" value="true"/>
				<param name="os_destination" value="/secure/Dashboard.jspa"/>
				<param name="login" value="Вход"/>
			</authconfig>
		</server>
	</servers>
	<settings>
		<smtp>
			<host>172.27.0.3</host>
			<port>25</port>
			<username>fdcadmin</username>
			<password>DulunsAdvu</password>
			<from>fdcadmin@fors.ru</from>
			<subject>Уведомление об отказе сервера sunny</subject>
			<msgTemplate>Некоторые сервреы вышли из строй на сервере sunny.fors.ru, а имеено:</msgTemplate>
		</smtp>
		<notifications>
		   <!-- deprecated-->
			<interval>1</interval>
			<emails>sahmed@fors.ru</emails>
		</notifications>
		<report>
			<name>report.html</name>
			<format>html</format>
		</report>
	</settings>
</config>

=== srecon/network-resource-monitoring/webserver-availability/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
	<servers>
		<server>
			<hostName>sunny.fors.ru</hostName>
			<port>80</port>
			<contextRoot>archiva</contextRoot>
			<protocol>http</protocol>
			<authconfig/>
		</server>
		<server>
			<hostName>sunny.fors.ru</hostName>
			<port>80</port>
			<contextRoot>jenkins</contextRoot>
			<protocol>http</protocol>
			<authconfig>
				<param name="j_username" value="sahmed"/>
				<param name="j_password" value="qwer$321"/>
			</authconfig>
		</server>
		<server>
			<hostName>sunny.fors.ru</hostName>
			<port>80</port>
			<contextRoot>sonar11</contextRoot>
			<protocol>http</protocol>
			<authconfig>
				<param name="login" value="sahmed"/>
				<param name="password" value="qwer4321"/>
				<param name="commit" value="Log+in"/>
				<param name="remember_me" value="1"/>
			</authconfig>
		</server>
	</servers>
	<settings>
		<smtp>
			<host>172.27.0.3</host>
			<port>25</port>
			<username>fdcadmin</username>
			<password>DulunsAdvu</password>
			<from>fdcadmin@fors.ru</from>
			<subject>Уведомление об отказе сервера sunny</subject>
			<msgTemplate>Некоторые сервреы вышли из строй на сервер sunny.fors.ru.</msgTemplate>
		</smtp>
		<notifications>
			<interval>10</interval>
			<emails>sahmed@fors.ru</emails>
		</notifications>
		<report>
			<name>report.html</name>
			<format>html</format>
		</report>
	</settings>
</config>
